# Deploy to Kubernetes - Review app with Azure DevSpaces
# Build and push image to Azure Container Registry; Deploy to Azure Kuberentes Services and setup Review App with Azure DevSpaces
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6321a02f-03f5-4c35-9e86-d050379d9730'
  imageRepository: 'sampleaksappimage'
  containerRegistry: 'sampleaksappcontainer.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'sampleaksappcontainer20656c89-auth'

  # Agent VM image name
  vmImageName: 'vs2017-win2016'
  
  # Azure Service connection
  azureConnection: '041cf974-d326-4d08-a067-eb1b5cd95552'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: charts
      artifact: charts

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'kadumuri1994pipelinesdotnetcoredocker-5312.sampleaksappnamespace'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: AzureCLI@2
            displayName: get host suffix
            inputs:
              scriptType: pscore
              scriptLocation: inlineScript
              azureSubscription: $(azureConnection)
              inlineScript: |
                $clusterId="/subscriptions/43320408-aff7-4a2c-bb49-9895135ebe43/resourcegroups/AKSClusters/providers/Microsoft.ContainerService/managedClusters/SampleAKSCluster"
                $resourceGroupName=$(cut -d '/' -f5 <<< "$clusterId")
                $clusterName=$(cut -d '/' -f9 <<< "$clusterId")
                az aks use-dev-spaces -n $clusterName -g $resourceGroupName -s sampleaksappnamespace -y
                $hostSuffix=$(azds show-context -o json | ConvertFrom-Json).controller.hostSuffix
                echo "##vso[task.setvariable variable=HostSuffix]$hostSuffix"

          - task: KubernetesManifest@0
            displayName: Bake manifests
            name: bake
            inputs:
              action: bake
              helmChart: $(Pipeline.Workspace)/charts/devspaces-v0.0.1.tgz
              overrides: |
                image.repository:$(containerRegistry)/$(imageRepository)
                service.port:8080 
                ingress.enabled:true
                ingress.hostname:app.$(HostSuffix)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(bake.manifestsBundle)
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

