apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
  namespace: default
  annotations:
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - image: sampleaksappcontainer.azurecr.io/sampleaksapprepo:latest
        name: sampleapp
        ports:
        - containerPort: 8080
