apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
  namespace: default
  annotations:
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - image: sampleakscluster-dns-42e9dd63.hcp.eastus.azmk8s.io/sampleapp:latest
        name: sampleapp
        ports:
        - containerPort: 8080
